apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpres-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.0.0.119
    path: /mnt/wordpress/wp

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-mysql-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.0.0.119
    path: /mnt/wordpress/db
